name: CI

on:
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
      - name: Run tests with coverage
        run: pnpm run test:coverage
        env:
          CI: true
      - name: Build
        run: yarn build
      - name: Lint
        uses: hallee/eslint-action@1.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  automerge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
